version: '2'

volumes:
    logs:
        driver: local

services:
    slim:
        image: php:7-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 8080:8080

            - .:/var/www

            - .:/app
        build:
            context: .
        env_file:
            - .env

    nginx:
        image: nginx:1.15.5-alpine
        ports:
            - "80:80"
        volumes:
            - .:/app
            - ./etc/infrastructure/nginx/site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    mysql:
        image: mysql:5.7.23
        ports:
            - "3306:3306"
        env_file:
            - .env

